# Generated by Django 4.0.2 on 2022-07-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('body', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/posts/')),
                ('room_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.roompost', verbose_name='RoomPost')),
            ],
        ),
    ]
