# Generated by Django 4.0.2 on 2022-05-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_roompostimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.roompost', verbose_name='RoomPost'),
        ),
    ]
