# Generated by Django 4.0.2 on 2022-05-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_roompostimage_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roompostimage',
            old_name='post',
            new_name='room_post',
        ),
    ]
