# Generated by Django 4.0.2 on 2022-08-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.room'),
        ),
    ]
