# Generated by Django 4.0.2 on 2022-03-10 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)])),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landlordprofile', verbose_name='Landlord')),
            ],
        ),
    ]
