# Generated by Django 4.0.2 on 2022-07-27 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('town', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('pin', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.room', verbose_name='Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='avatar_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='hostels.roomimage', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landlordprofile', verbose_name='Landlord'),
        ),
    ]
