# Generated by Django 4.0.2 on 2022-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_rename_landlord_room_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
    ]
