# Generated by Django 4.0.2 on 2022-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_room_address_alter_room_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='hostels.roomimage', verbose_name='Avatar'),
        ),
    ]
