# Generated by Django 4.0.2 on 2022-04-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_alter_roomimage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.room', verbose_name='Room'),
        ),
    ]
